# SPDX-License-Identifier: Apache-2.0
# Originally developed by Telicent Ltd.; subsequently adapted, enhanced, and maintained by the National Digital Twin Programme.

# Copyright (c) Telicent Ltd.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Modifications made by the National Digital Twin Programme (NDTP)
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

include:
  - docker-grpc-resources/docker-compose-shared.yml

name: grpc
services:
  federator-server:
#    image: uk.gov.dbt.ndtp/${ARTIFACT_ID}-server:${VERSION}
    image: ghcr.io/national-digital-twin/federator/federator-server:0.90.0
    container_name: federator-server
    environment:
      FEDERATOR_SERVER_PROPERTIES: /config/server.properties
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - core
    depends_on:
      kafka-src:
        condition: service_healthy
    volumes:
      - ./docker-grpc-resources/access.json:/config/access.json
      - ./docker-grpc-resources/server.properties:/config/server.properties
      - ./filter:/library
    restart: on-failure

  federator-client:
#    image: uk.gov.dbt.ndtp/${ARTIFACT_ID}-client:${VERSION}
    image: ghcr.io/national-digital-twin/federator/federator-client:0.90.0
    container_name: federator-client
    environment:
      FEDERATOR_CLIENT_PROPERTIES: /config/client.properties
    networks:
      - core
    volumes:
      - ./docker-grpc-resources/client.properties:/config/client.properties
      - ./docker-grpc-resources/connection-configuration.json:/config/connection-configuration.json
    depends_on:
      redis:
        condition: service_healthy
      kafka-target:
        condition: service_healthy
      kafka-topics-populator:
        condition: service_completed_successfully
      federator-server:
        condition: service_started
    restart: on-failure

  kafka-message-counter:
    build:
      context: kafka-message-counter
      dockerfile: Dockerfile
    container_name: kafka-message-counter
    depends_on:
      federator-client:
        condition: service_started
      kafka-topics-populator:
        condition: service_completed_successfully
    environment:
      KAFKA_BROKER_SERVER: "kafka-target:19092"
      TOPICS_TO_CHECK: "federated-FederatorServer1-knowledge"
      EXPECTED_MESSAGE_COUNTS: "23"
      DELAY_BEFORE_CONSUMING_DATA: "10"
    networks:
      - core
    volumes:
      - ../input:/usr/bin/input
