# SPDX-License-Identifier: Apache-2.0
# Originally developed by Telicent Ltd.; subsequently adapted, enhanced, and maintained by the National Digital Twin Programme.

# Copyright (c) Telicent Ltd.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Modifications made by the National Digital Twin Programme (NDTP)
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

include:
  - docker-grpc-resources/docker-compose-shared.yml

name: grpc-multi-client-multi-server
services:

  zookeeper-target-2:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper-target-2
    environment:
      ZOOKEEPER_CLIENT_PORT: 32183
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: "zookeeper-target:2888:3888"
    networks:
      - core
    ports:
      - "32183:32183"
    hostname: zookeeper-target-2
    restart: on-failure

  kafka-target-2:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka-target-2
    environment:
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL_DOCKER_INTERNAL://localhost:29094,LISTENER_DOCKER_INTERNAL://kafka-target-2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-target-2:32183"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
    ports:
      - "29094:29094"
    healthcheck:
      test: "kafka-topics --list --bootstrap-server localhost:9094 || exit 1"
      interval: 1s
      timeout: 60s
      retries: 60
    networks:
      - core
    depends_on:
      - zookeeper-target-2
    restart: on-failure

  federator-server-1:
    image: uk.gov.dbt.ndtp/${ARTIFACT_ID}-server:${VERSION}
    container_name: federator-server-1
    environment:
      FEDERATOR_SERVER_PROPERTIES: /config/server.properties
    networks:
      - core
    depends_on:
      kafka-src:
        condition: service_healthy
      kafka-topics-populator:
        condition: service_completed_successfully
    volumes:
      - ./docker-grpc-resources/multiple-clients-multiple-server/server.properties:/config/server.properties
      - ./filter:/library
    restart: on-failure

  federator-server-2:
    image: uk.gov.dbt.ndtp/${ARTIFACT_ID}-server:${VERSION}
    container_name: federator-server-2
    environment:
      FEDERATOR_SERVER_PROPERTIES: /config/server.properties
    networks:
      - core
    depends_on:
      kafka-src:
        condition: service_healthy
      kafka-topics-populator:
        condition: service_completed_successfully
    volumes:
      - ./docker-grpc-resources/multiple-clients-multiple-server/server.properties:/config/server.properties
      - ./filter:/library
    restart: on-failure

  federator-client-1:
    image: uk.gov.dbt.ndtp/${ARTIFACT_ID}-client:${VERSION}
    container_name: federator-client-1
    environment:
      FEDERATOR_CLIENT_PROPERTIES: /config/client.properties
    networks:
      - core
    volumes:
      - ./docker-grpc-resources/multiple-clients-multiple-server/client1.properties:/config/client.properties
      - ./docker-grpc-resources/multiple-clients-multiple-server/connection-configuration1.json:/config/connection-configuration.json
    depends_on:
      redis:
        condition: service_healthy
      kafka-target:
        condition: service_healthy
      kafka-topics-populator:
        condition: service_completed_successfully
      federator-server-1:
        condition: service_started
      federator-server-2:
        condition: service_started
    restart: on-failure

  federator-client-2:
    image: uk.gov.dbt.ndtp/${ARTIFACT_ID}-client:${VERSION}
    container_name: federator-client-2
    environment:
      FEDERATOR_CLIENT_PROPERTIES: /config/client.properties
    networks:
      - core
    volumes:
      - ./docker-grpc-resources/multiple-clients-multiple-server/client2.properties:/config/client.properties
      - ./docker-grpc-resources/multiple-clients-multiple-server/connection-configuration2.json:/config/connection-configuration.json
    depends_on:
      redis:
        condition: service_healthy
      kafka-target-2:
        condition: service_healthy
      kafka-topics-populator:
        condition: service_completed_successfully
      federator-server-1:
        condition: service_started
      federator-server-2:
        condition: service_started
    restart: on-failure

  kafka-message-counter:
    build:
      context: kafka-message-counter
      dockerfile: Dockerfile
    container_name: kafka-message-counter
    depends_on:
      kafka-bulk-test-data-loader:
        condition: service_completed_successfully
      federator-client-1:
        condition: service_started
      federator-client-2:
        condition: service_started
    environment:
      KAFKA_BROKER_SERVER: "kafka-target:19092"
      TOPICS_TO_CHECK: "federated-client1-FederatorServer1-knowledge federated-client1-FederatorServer1-knowledge1 federated-client1-FederatorServer2-knowledge1 federated-client1-FederatorServer2-knowledge2"
      EXPECTED_MESSAGE_COUNTS: "12 2 2 4"
      DELAY_BEFORE_CONSUMING_DATA: "5"
    networks:
      - core
    volumes:
      - ../input:/usr/bin/input

  kafka-message-counter-2:
    build:
      context: kafka-message-counter
      dockerfile: Dockerfile
    container_name: kafka-message-counter-2
    depends_on:
      kafka-bulk-test-data-loader:
        condition: service_completed_successfully
      federator-client-1:
        condition: service_started
      federator-client-2:
        condition: service_started
    environment:
      KAFKA_BROKER_SERVER: "kafka-target-2:19092"
      TOPICS_TO_CHECK: "federated-client2-FederatorServer2-knowledge federated-client2-FederatorServer1-knowledge2"
      EXPECTED_MESSAGE_COUNTS: "12 13"
      DELAY_BEFORE_CONSUMING_DATA: "5"
    networks:
      - core
    volumes:
      - ../input:/usr/bin/input
